### ISSUE TITLE
Make an input.lua so i wont suffer 

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [ogwayTheMagnificent/Bizon19-s-Lua-Obfuscator#1]
MAKE AN INPUT.LUA I DO NOT KNOW HOW TO SCRIPT ALL OF MY SCRIPTS ARE 500% SKIDDED AND WHEN I USE PRINT IT DONT EVEN WORK

**Comment by ogwayTheMagnificent** [comment]
try finding the function "local code = function()" then just put your code under it, its really complicated cuz of string.dump since this obfuscator doesnt have a custom bc
